::Const.World.Common.WorldEconomy.AmountOfLeakedCaravanInventoryInfo = 10;

::Z.Economy.CaravanTable <- {
	"trade_goods" : {
		"Min" : 1,
		"Max" : 3,
		"Table" : [
			"scripts/items/trade/iron_ingots_item"
		],
		"TableRare" : [
			"scripts/items/trade/gold_ingots_item"
		]
	},

	"misc" : {
		"Min" : 2,
		"Max" : 4,
		"Table" : [
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",

			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",
			"scripts/items/misc/happy_powder_item",

			"scripts/items/ammo/large_quiver_of_bolts",
			"scripts/items/ammo/huge_quiver_of_bolts",
			"scripts/items/ammo/large_powder_bag",
			"scripts/items/ammo/huge_quiver_of_bolts",
			"scripts/items/weapons/crossbow",
			"scripts/items/weapons/heavy_crossbow",
			"scripts/items/weapons/oriental/handgonne",
			"scripts/items/misc/scroll",
			"scripts/items/misc/potion_of_oblivion_item",
			"scripts/items/misc/potion_of_oblivion_fake_item",
		],
		"TableRare" : [
			"scripts/items/weapons/named/named_handgonne",
			"scripts/items/accessory/ring/cloranthy_ring",
			"scripts/items/accessory/ring/master_ring",
			"scripts/items/accessory/ring/executioner_ring",
			"scripts/items/accessory/ring/slyph_ring",
			"scripts/items/misc/anatomist/nachzehrer_potion_item",
			"scripts/items/misc/anatomist/direwolf_potion_item",
			"scripts/items/misc/tome",

			"scripts/items/weapons/named/named_axe",
			"scripts/items/weapons/named/named_cleaver",
			"scripts/items/weapons/named/named_greataxe",
			"scripts/items/weapons/named/named_greatsword",
			"scripts/items/weapons/named/named_mace",
			"scripts/items/weapons/named/named_spear",
			"scripts/items/weapons/named/named_sword",
			"scripts/items/weapons/named/named_longsword",
			"scripts/items/weapons/named/named_two_handed_hammer",
			"scripts/items/weapons/named/named_pike",
			"scripts/items/weapons/named/legend_named_longsword",
			"scripts/items/weapons/named/legend_named_swordstaff",
			"scripts/items/weapons/named/legend_named_halberd",
			"scripts/items/weapons/named/legend_named_voulge",
			"scripts/items/weapons/named/legend_named_warhammer",
			"scripts/items/weapons/named/legend_named_gladius",
			"scripts/items/weapons/named/legend_named_military_goedendag",

			"scripts/items/weapons/named/named_crossbow",
			"scripts/items/weapons/named/named_warbow",
			"scripts/items/weapons/named/named_crossbow",
			"scripts/items/weapons/named/named_warbow",
			"scripts/items/weapons/named/named_crossbow",
			"scripts/items/weapons/named/named_warbow",
			"scripts/items/weapons/named/named_crossbow",
			"scripts/items/weapons/named/named_warbow",
			"scripts/items/weapons/named/named_crossbow",
			"scripts/items/weapons/named/named_warbow",
		]
	},

	"melee_weapons" : {
		"Min" : 1,
		"Max" : 3,
		"Table" : [
			"scripts/items/weapons/boar_spear",
			"scripts/items/weapons/fighting_spear",
			"scripts/items/weapons/hand_axe",
			"scripts/items/weapons/shortsword",
			"scripts/items/weapons/shortsword",
			"scripts/items/weapons/pike",
			"scripts/items/weapons/pike",
			"scripts/items/weapons/billhook",
			"scripts/items/weapons/longaxe",
			"scripts/items/weapons/falchion",
			"scripts/items/weapons/falchion",
			"scripts/items/weapons/morning_star",
			"scripts/items/weapons/morning_star",
			"scripts/items/weapons/arming_sword",
			"scripts/items/weapons/legend_parrying_dagger",
			"scripts/items/weapons/arming_sword",
			"scripts/items/weapons/military_cleaver",
			"scripts/items/weapons/winged_mace",
			"scripts/items/weapons/fighting_axe",
			"scripts/items/weapons/noble_sword",
			"scripts/items/weapons/military_pick",
			"scripts/items/weapons/warhammer",
			"scripts/items/weapons/flail",
			"scripts/items/weapons/greatsword",
			"scripts/items/weapons/warbrand",
			"scripts/items/weapons/greataxe",
			"scripts/items/weapons/two_handed_hammer",
			"scripts/items/weapons/legend_glaive",
			"scripts/items/weapons/legend_battle_glaive",
			"scripts/items/weapons/legend_swordstaff",
			"scripts/items/weapons/legend_halberd",
			"scripts/items/weapons/legend_military_voulge",
			"scripts/items/weapons/legend_ranged_flail",
			"scripts/items/weapons/legend_ranged_wooden_flail",
			"scripts/items/weapons/legend_voulge",
			"scripts/items/weapons/longsword",
			"scripts/items/weapons/legend_longsword",
			"scripts/items/weapons/flail",
			"scripts/items/weapons/two_handed_flail",
			"scripts/items/weapons/spetum",
			"scripts/items/weapons/polehammer",
			"scripts/items/weapons/legend_military_goedendag",
			"scripts/items/weapons/fencing_sword",
			"scripts/items/weapons/legend_estoc",
			"scripts/items/weapons/bardiche",
			"scripts/items/weapons/scimitar",
			"scripts/items/weapons/shamshir",
		],
		"TableRare" : [
			"scripts/items/weapons/named/named_axe",
			"scripts/items/weapons/named/named_cleaver",
			"scripts/items/weapons/named/named_greataxe",
			"scripts/items/weapons/named/named_greatsword",
			"scripts/items/weapons/named/named_mace",
			"scripts/items/weapons/named/named_spear",
			"scripts/items/weapons/named/named_sword",
			"scripts/items/weapons/named/named_longsword",
			"scripts/items/weapons/named/named_two_handed_hammer",
			"scripts/items/weapons/named/named_pike",
			"scripts/items/weapons/named/legend_named_longsword",
			"scripts/items/weapons/named/legend_named_swordstaff",
			"scripts/items/weapons/named/legend_named_halberd",
			"scripts/items/weapons/named/legend_named_voulge",
			"scripts/items/weapons/named/legend_named_warhammer",
			"scripts/items/weapons/named/legend_named_gladius",
			"scripts/items/weapons/named/legend_named_military_goedendag",
		]
	},

	"ranged_weapons" : {
		"Min" : 1,
		"Max" : 3,
		"Table" : [
			"scripts/items/trade/iron_ingots_item",
			"scripts/items/weapons/hunting_bow",
			"scripts/items/weapons/war_bow",
		],
		"TableRare" : [
			"scripts/items/weapons/named/named_warbow",
		]
	},

	"armor" : {
		"Min" : 1,
		"Max" : 3,
		"Table" : [
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood_full",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood_full",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood_full",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood_full",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood_full",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood_full",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood_full",
			"scripts/items/legend_helmets/hood/legend_helmet_chain_hood_full",
			"scripts/items/legend_helmets/helm/legend_helmet_great_helm",
			"scripts/items/legend_helmets/helm/legend_helmet_great_helm",

			"scripts/items/legend_helmets/top/legend_helmet_faceplate_winged",
			"scripts/items/legend_helmets/top/legend_helmet_faceplate_snub_slit",
			"scripts/items/legend_helmets/top/legend_helmet_faceplate_sharp",
			"scripts/items/legend_helmets/top/legend_helmet_faceplate_gold",
			"scripts/items/legend_helmets/top/legend_helmet_faceplate_full",
			"scripts/items/legend_helmets/top/legend_helmet_faceplate_full_gold",
			"scripts/items/legend_helmets/top/legend_helmet_chain_attachment",

			"scripts/items/legend_armor/chain/legend_armor_hauberk_full",
			"scripts/items/legend_armor/chain/legend_armor_hauberk_full",
			"scripts/items/legend_armor/chain/legend_armor_hauberk_full",
			"scripts/items/legend_armor/chain/legend_armor_hauberk_full",
			"scripts/items/legend_armor/chain/legend_armor_hauberk_full",
			"scripts/items/legend_armor/chain/legend_armor_hauberk_full",
			"scripts/items/legend_armor/chain/legend_armor_hauberk_full",
			"scripts/items/legend_armor/cloth/legend_tunic_noble",
			"scripts/items/legend_armor/cloth/legend_tunic_noble",
			"scripts/items/legend_armor/cloth/legend_padded_surcoat",
			"scripts/items/legend_armor/cloth/legend_padded_surcoat",
			"scripts/items/legend_armor/cloth/legend_padded_surcoat",
			"scripts/items/legend_armor/cloth/legend_gambeson",
			"scripts/items/legend_armor/cloth/legend_gambeson",
			"scripts/items/legend_armor/cloth/legend_gambeson",
			"scripts/items/legend_armor/plate/legend_armor_plate_full",
			"scripts/items/legend_armor/plate/legend_armor_plate_full",			
		],
		"TableRare" : [
			"scripts/items/legend_helmets/top/legend_helmet_golden_helm",
			"scripts/items/legend_helmets/top/legend_helmet_faceplate_full_gold",
			"scripts/items/legend_helmets/top/legend_helmet_faceplate_full_01_named",
			"scripts/items/legend_helmets/top/legend_helmet_bascinet_visor_named",
			"scripts/items/legend_helmets/top/legend_helmet_bascinet_visor_named",

			"scripts/items/legend_armor/cloth/legend_tunic_noble_named",
			"scripts/items/legend_armor/named/legend_armor_cloak_rich",
			"scripts/items/legend_armor/named/legend_armor_named_tabard",
			"scripts/items/legend_armor/named/legend_named_noble_mail_armor",
			"scripts/items/legend_armor/plate/legend_armor_plate_full_greaves_named",
		]
	},
	
};