import os
import re
from pathlib import Path

FILE_BLACKLIST = {
    'adopt_wardog_event',
    'butcher_vs_wardog_event',
    'butcher_wardogs_event',
    'dogfighting_event',
    'dogs_dig_up_loot_event',
    'houndmaster_tames_wolf_event',
    'houndmaster_tames_white_wolf_event',
    'wardogs_fight_each_other_event',
    'aging_swordmaster_event',
    'aging_swordmaster_paycut_event',
    'aging_swordmaster_preview_event',
    'all_naked_event',
    'beat_up_old_man_event',
    'bowyer_crafts_masterwork_event',
    'childrens_crusade_event',
    'come_across_ritual_event',
    'cultist_finale_event',
    'cultist_vs_old_gods_event',
    'cultist_vs_uneducated_event',
    'drunkard_loses_stuff_event',
    'melon_thief_event',
    'player_is_rich_op_backgrounds_event',
    'player_is_rich_event',
    'player_is_sent_for_event',
    'player_plays_dice_event',
    'raid_farmstead_event',
    'ratcatcher_crafts_net_event',
    'wound_heals_event',
    'addict_steals_potion_event',
    'alp_captured_in_hole_event',
    'collector_wants_trophy_event',
    'gain_addiction_event',
    'glutton_eats_apple_event',
    'kid_blacksmith_event',
    'lose_addiction_event',
    'monk_crafts_holy_water_event',
    'schrat_exposition_event',
    'spooky_forest_event',
    'unhold_exposition_event',
    'webknecht_exposition_event',
    'youngling_alp_event',
    'adopt_warhound_event',
    'cultist_origin_armor_event',
    'cultist_origin_finale_event',
    'cultist_origin_flock_event',
    'cultist_origin_hood_event',
    'cultist_origin_sacrifice_event',
    'cultist_origin_vs_old_gods_event',
    'cultist_origin_vs_uneducated_event',
    'traveler_north_event',
    'wild_dog_sounds_event',
    'cultish_arrangement_event',
    'gunpowder_wagon_event',
    'manhunters_origin_capture_prisoner_event',
    'read_black_book_event',
    'trade_black_book_event',
    'traveler_south_event',
    'sellsword_retires_event',
    'oathbreaker_event',
    'tree_fort_event',
    'volunteers_event',
    'legend_alchemist_crafts_thing_event',
    'legend_blacksmith_craft_armor',
    'legend_blacksmith_crafts_crusadersword',
    'legend_blacksmith_fix_equipment',
    'legend_blacksmith_reforges_orc_cleaver_event',
    'legend_butcher_vs_donkey',
    'legend_cabal_puppet_event',
    'legend_cannibal_eats_part_of_brother',
    'legend_clothing_merchant_event',
    'legend_falconflies_event',
    'legend_inventor_prosthetic_ear',
    'legend_inventor_prosthetic_eye',
    'legend_inventor_prosthetic_finger',
    'legend_inventor_prosthetic_foot',
    'legend_inventor_prosthetic_forearm',
    'legend_inventor_prosthetic_hand',
    'legend_inventor_prosthetic_leg',
    'legend_inventor_prosthetic_nose',
    'legend_rat_bite_event',
    'legend_swordmaster_fav_enemy_event',
    'legend_trader_recruitment',
    'legend_traveling_bard_event',
    'legends_adopt_warbear_event',
    'legends_fletcher_crafts_masterwork_event',
    'legends_minstrel_and_juggler_event',
    'legends_minstrel_and_troubador_event',
    'legends_troubador_and_juggler_event',
    'dog_in_swamp_event',
    'anatomist_vs_dog_event',
    'alp_nightmare1_event',
    'alp_nightmare2_event',
}

r'aging_swordmaster_paycut_event.nut'

for root, dirs, files in os.walk('scripts/events/events'):
     for file in files:
        if file.replace('.nut', '') in FILE_BLACKLIST:
            print(f'deleted {os.path.join(root, file)}')
            os.remove(os.path.join(root, file))
