import os
import re
from pathlib import Path

parse = r'''//Disable general events
::mods_hookExactClass("events/events/adopt_wardog_event", function (o){ o.onUpdateScore = function() { return; }});
::mods_hookExactClass("events/events/butcher_vs_wardog_event", function (o){ o.onUpdateScore = function() { return; }});
::mods_hookExactClass("events/events/butcher_wardogs_event", function (o){ o.onUpdateScore = function() { return; }});
::mods_hookExactClass("events/events/dogfighting_event", function (o){ o.onUpdateScore = function() { return; }});
::mods_hookExactClass("events/events/dogs_dig_up_loot_event", function (o){ o.onUpdateScore = function() { return; }});
::mods_hookExactClass("events/events/houndmaster_tames_wolf_event", function (o){ o.onUpdateScore = function() { return; }});
::mods_hookExactClass("events/events/houndmaster_tames_white_wolf_event", function (o){ o.onUpdateScore = function() { return; }});
::mods_hookExactClass("events/events/wardogs_fight_each_other_event", function (o){ o.onUpdateScore = function() { return; }});
::mods_hookExactClass("events/events/aging_swordmaster_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/aging_swordmaster_paycut_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/aging_swordmaster_preview_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/all_naked_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/beat_up_old_man_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/bowyer_crafts_masterwork_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/childrens_crusade_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/come_across_ritual_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/cultist_finale_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/cultist_vs_old_gods_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/cultist_vs_uneducated_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/drunkard_loses_stuff_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/melon_thief_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/player_is_rich_op_backgrounds_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/player_is_rich_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/player_is_sent_for_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/player_plays_dice_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/raid_farmstead_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/ratcatcher_crafts_net_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/wound_heals_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/addict_steals_potion_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/alp_captured_in_hole_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/collector_wants_trophy_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/gain_addiction_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/glutton_eats_apple_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/kid_blacksmith_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/lose_addiction_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/monk_crafts_holy_water_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/schrat_exposition_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/spooky_forest_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/unhold_exposition_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/webknecht_exposition_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/youngling_alp_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc4/adopt_warhound_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc4/cultist_origin_armor_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc4/cultist_origin_finale_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc4/cultist_origin_flock_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc4/cultist_origin_hood_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc4/cultist_origin_sacrifice_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc4/cultist_origin_vs_old_gods_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc4/cultist_origin_vs_uneducated_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc4/traveler_north_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc4/wild_dog_sounds_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc6/cultish_arrangement_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc6/gunpowder_wagon_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc6/manhunters_origin_capture_prisoner_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc6/read_black_book_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc6/trade_black_book_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc6/traveler_south_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc6/sellsword_retires_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc8/oathbreaker_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc8/tree_fort_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc8/volunteers_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_alchemist_crafts_thing_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_blacksmith_craft_armor", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_blacksmith_crafts_crusadersword", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_blacksmith_fix_equipment", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_blacksmith_reforges_orc_cleaver_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_butcher_vs_donkey", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_cabal_puppet_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_cannibal_eats_part_of_brother", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_clothing_merchant_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_falconflies_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_inventor_prosthetic_ear", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_inventor_prosthetic_eye", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_inventor_prosthetic_finger", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_inventor_prosthetic_foot", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_inventor_prosthetic_forearm", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_inventor_prosthetic_hand", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_inventor_prosthetic_leg", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_inventor_prosthetic_nose", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_rat_bite_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_swordmaster_fav_enemy_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_trader_recruitment", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legend_traveling_bard_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legends_adopt_warbear_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legends_fletcher_crafts_masterwork_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legends_minstrel_and_juggler_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legends_minstrel_and_troubador_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/legends/legends_troubador_and_juggler_event", function(o) { o.onUpdateScore = function(){ return; }});
::mods_hookExactClass("events/events/dlc2/dog_in_swamp_event", function (o){ o.onUpdateScore = function() { return; }});
::mods_hookExactClass("events/events/dlc8/anatomist_vs_dog_event", function (o){ o.onUpdateScore = function() { return; }});
//::mods_hookExactClass("events/events/dlc2/alp_nightmare1_event", function(o) { o.onUpdateScore = function(){ return; }});
//::mods_hookExactClass("events/events/dlc2/alp_nightmare2_event", function(o) { o.onUpdateScore = function(){ return; }});'''

lines = parse.split('\n')
for line in lines:
    if not '::mods_hookExactClass(' in line: continue
    id = line.replace('::mods_hookExactClass("events/events/', '').replace('", function (o){ o.onUpdateScore = function() { return; }});', '').replace('", function(o) { o.onUpdateScore = function(){ return; }});', '')
    id = re.sub(r'.*\/', '', id)
    print( f'\'{id}\',' )
