::mods_hookExactClass("entity/world/settlements/legends_steppe_village.nut", function(o) {
	o.create = function()
	{
		this.legends_village.create();
		this.m.Names = [
			[
				"Wohlen",
				"Krauchthal",
				"Brunnenthal",
				"Erlach",
				"Treiten",
				"Pilgerort",
				"Heiligort",
				"Trocken",
				"Barbarisch",
				"Dunkelhautig",
				"Tentlingen",
				"Himmelsdorf",
				"Thurn",
				"Subingen",
				"Thunstetten",
				"Rothenbach",
				"Sandheim",
				"Sonstedt",
				"Siegau",
				"Strohdorf",
				"Sonnheim",
				"Sandfels",
				"Sonnfels",
				"Attendorn",
				"Strauchdorf",
				"Kargau",
				"Sudheim",
				"Krauchdorf",
				"Dornen",
				"Dornthal",
				"Dornheim"
			],
			[
				"Wohlen",
				"Krauchthal",
				"Brunnenthal",
				"Erlach",
				"Treiten",
				"Tentlingen",
				"Himmelsdorf",
				"Thurn",
				"Subingen",
				"Thunstetten",
				"Rothenbach",
				"Sandheim",
				"Sonstedt",
				"Siegau",
				"Strohdorf",
				"Sonnheim",
				"Sandfels",
				"Sonnfels",
				"Strauchdorf",
				"Kargau",
				"Attendorn",
				"Sudheim",
				"Krauchdorf",
				"Dornen",
				"Dornthal",
				"Dornheim"
			],
			[
				"Wunderstadt",
				"Wohlstadt",
				"Brunnstadt",
				"Erlstadt",
				"Himmelstadt",
				"Sandstadt",
				"Dornen",
				"Rothstadt",
				"Gelbstadt",
				"Krautmark",
				"Suderstadt",
				"Sonstadt",
				"Strohmark",
				"Sandmark",
				"Sonnmark",
				"Grafenschein",
				"Hellstadt",
				"Lichtmark",
				"Dornland",
				"Rothenmark",
				"Brunnenland"
			]
		];
		this.m.DraftLists = [
			[
				"apprentice_background",
				"beggar_background",
				"brawler_background",
				"caravan_hand_background",
				"gambler_background",
				"daytaler_background",
				"daytaler_background",
				"peddler_background",
				"refugee_background",
				"tailor_background",
				"thief_background",
				"vagabond_background",
				"poacher_background",
				"apprentice_background",
				"brawler_background",
				"caravan_hand_background",
				"gambler_background",
				"peddler_background",
				"refugee_background",
				"vagabond_background",
				"poacher_background"
			],
			[
				"apprentice_background",
				"beggar_background",
				"bowyer_background",
				"caravan_hand_background",
				"caravan_hand_background",
				"gambler_background",
				"daytaler_background",
				"daytaler_background",
				"historian_background",
				"hunter_background",
				"mason_background",
				"militia_background",
				"minstrel_background",
				"peddler_background",
				"ratcatcher_background",
				"refugee_background",
				"refugee_background",
				"servant_background",
				"tailor_background",
				"thief_background",
				"vagabond_background",
				"adventurous_noble_background",
				"cripple_background",
				"poacher_background",
				"apprentice_background",
				"caravan_hand_background",
				"caravan_hand_background",
				"gambler_background",
				"historian_background",
				"hunter_background",
				"mason_background",
				"militia_background",
				"peddler_background",
				"ratcatcher_background",
				"refugee_background",
				"refugee_background",
				"vagabond_background",
				"cripple_background",
				"poacher_background"
			],
			[
				"apprentice_background",
				"caravan_hand_background",
				"caravan_hand_background",
				"caravan_hand_background",
				"gambler_background",
				"gravedigger_background",
				"graverobber_background",
				"historian_background",
				"hunter_background",
				"juggler_background",
				"militia_background",
				"militia_background",
				"militia_background",
				"minstrel_background",
				"minstrel_background",
				"flagellant_background",
				"peddler_background",
				"peddler_background",
				"ratcatcher_background",
				"refugee_background",
				"refugee_background",
				"servant_background",
				"shepherd_background",
				"thief_background",
				"vagabond_background",
				"bastard_background",
				"raider_background",
				"retired_soldier_background",
				"sellsword_background",
				"swordmaster_background",
				"cripple_background",
				"eunuch_background",
				"legend_inventor_background"
			]
		];
		this.m.FemaleDraftLists = [
			[
				"female_beggar_background",
				"female_daytaler_background",
				"female_daytaler_background",
				"female_tailor_background",
				"female_thief_background"
			],
			[
				"female_beggar_background",
				"female_bowyer_background",
				"female_daytaler_background",
				"female_daytaler_background",
				"female_minstrel_background",
				"female_servant_background",
				"female_tailor_background",
				"female_thief_background",
				"female_adventurous_noble_background"
			],
			[
				"female_beggar_background",
				"female_beggar_background",
				"female_bowyer_background",
				"female_daytaler_background",
				"female_tailor_background",
				"female_adventurous_noble_background",
				"female_adventurous_noble_background",
				"female_disowned_noble_background"
			]
		];
		this.m.StablesLists = [
			[
				"legend_donkey_background",
				"legend_horse_rouncey",
				"legend_horse_destrier",
				"legend_horse_courser"
			],
			[],
			[]
		];

		if (this.Const.DLC.Unhold)
		{
			this.m.DraftLists[0].push("beast_hunter_background");
			this.m.DraftLists[1].push("beast_hunter_background");
			this.m.DraftLists[2].push("beast_hunter_background");
		}

		this.m.Rumors = this.Const.Strings.RumorsSteppeSettlement;
	}

});
