::mods_hookExactClass("entity/world/settlements/legends_fishing_village.nut", function(o) {
	o.create = function()
	{
		this.legends_village.create();
		this.m.Names = [
			[
				"Seedorf",
				"Kielseng",
				"Meierwik",
				"Fischschlachten",
				"Schiffdrucken",
				"Schiffbauen",
				"Nassort",
				"Sanddorf",
				"Sandwik",
				"Holnis",
				"Holmwik",
				"Niewik",
				"Hattlund",
				"Stohl",
				"Strande",
				"Sandkamp",
				"Sandberg",
				"Birkenstrand",
				"Sundheim",
				"Seekamp",
				"Krakendorf",
				"Blankwasser",
				"Harkensee",
				"Otterndorf",
				"Seefeld",
				"Horum",
				"Krumhorn",
				"Gothmund",
				"Angeln",
				"Sandholm",
				"Jadensee",
				"Egernsande",
				"Nebelheim",
				"Sudersande",
				"Grossenkoog",
				"Aalbek",
				"Seedeich"
			],
			[
				"Seedock",
				"Wikhavn",
				"Sandhoom",
				"Sandkai",
				"Holnishovn",
				"Holmwader",
				"Niewekai",
				"Stohlhoven",
				"Strandekai",
				"Kampwader",
				"Birkhaven",
				"Sundkajung",
				"Seehoben",
				"Krakenwader",
				"Blankhoom",
				"Harkendock",
				"Krumwader",
				"Saltkai",
				"Salthaven",
				"Grotenhoom",
				"Lutendock",
				"Kaiwader",
				"Singhoben",
				"Weissenhaven",
				"Tiefenhaven",
				"Wasserkoog",
				"Osterstrande",
				"Steinhaven",
				"Duhnenhaven",
				"Neudeich",
				"Sandehaven"
			],
			[
				"Seestadt",
				"Wikstadt",
				"Konigshaven",
				"Grafenhaven",
				"Holnisland",
				"Nieweland",
				"Kampstadt",
				"Krakenland",
				"Blankenstadt",
				"Harkenstadt",
				"Tiefenstadt",
				"Weissenstadt",
				"Kobmanhaven",
				"Grotenhaven",
				"Konigswasser",
				"Konigsmunde",
				"Kronenkoog",
				"Steinkai",
				"Deichstadt"
			]
		];
		this.m.DraftLists = [
			[
				"beggar_background",
				"beggar_background",
				"daytaler_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"gravedigger_background",
				"peddler_background",
				"tailor_background",
				"vagabond_background",
				"vagabond_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"gravedigger_background",
				"peddler_background",
				"vagabond_background",
				"vagabond_background"
			],
			[
				"apprentice_background",
				"beggar_background",
				"beggar_background",
				"brawler_background",
				"caravan_hand_background",
				"daytaler_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"gravedigger_background",
				"graverobber_background",
				"historian_background",
				"juggler_background",
				"killer_on_the_run_background",
				"messenger_background",
				"militia_background",
				"monk_background",
				"peddler_background",
				"flagellant_background",
				"ratcatcher_background",
				"refugee_background",
				"servant_background",
				"tailor_background",
				"thief_background",
				"vagabond_background",
				"cripple_background",
				"eunuch_background",
				"sellsword_background",
				"apprentice_background",
				"brawler_background",
				"caravan_hand_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"gravedigger_background",
				"graverobber_background",
				"historian_background",
				"juggler_background",
				"killer_on_the_run_background",
				"messenger_background",
				"militia_background",
				"monk_background",
				"peddler_background",
				"flagellant_background",
				"ratcatcher_background",
				"refugee_background",
				"vagabond_background",
				"cripple_background",
				"eunuch_background",
				"sellsword_background"
			],
			[
				"apprentice_background",
				"brawler_background",
				"caravan_hand_background",
				"caravan_hand_background",
				"gambler_background",
				"cultist_background",
				"fisherman_background",
				"fisherman_background",
				"fisherman_background",
				"gravedigger_background",
				"graverobber_background",
				"historian_background",
				"juggler_background",
				"killer_on_the_run_background",
				"mason_background",
				"messenger_background",
				"militia_background",
				"militia_background",
				"minstrel_background",
				"monk_background",
				"cripple_background",
				"eunuch_background",
				"peddler_background",
				"flagellant_background",
				"ratcatcher_background",
				"refugee_background",
				"vagabond_background",
				"bastard_background",
				"raider_background",
				"raider_background",
				"retired_soldier_background",
				"sellsword_background",
				"swordmaster_background",
				"legend_inventor_background"
			]
		];
		this.m.FemaleDraftLists = [
			[
				"female_beggar_background",
				"female_beggar_background",
				"female_daytaler_background",
				"female_butcher_background",
				"female_butcher_background",
				"female_tailor_background"
			],
			[
				"female_beggar_background",
				"female_beggar_background",
				"female_daytaler_background",
				"female_butcher_background",
				"female_butcher_background",
				"female_servant_background",
				"female_tailor_background",
				"female_thief_background"
			],
			[
				"female_beggar_background",
				"female_beggar_background",
				"female_daytaler_background",
				"female_daytaler_background",
				"female_butcher_background",
				"female_butcher_background",
				"female_servant_background",
				"female_servant_background",
				"female_tailor_background",
				"female_thief_background",
				"female_adventurous_noble_background",
				"female_disowned_noble_background"
			]
		];
		this.m.StablesLists = [
			[],
			[],
			[]
		];
		this.m.Rumors = this.Const.Strings.RumorsFishingSettlement;
		this.m.ProduceString = "fish";
	}

	o.getHousesMin = function()
	{
		switch(this.m.Size)
		{
		case 1:
			return 1;

		case 2:
			return 2;

		case 3:
			return 4;
		}

		return 1;
	}

});
