::mods_hookExactClass("entity/world/settlements/legends_tundra_fort.nut", function(o) {
	o.create = function()
	{
		this.legends_fort.create();
		this.m.Names = [
			[
				"Tonderwold",
				"Hornwold",
				"Grimtorn",
				"Helleweir",
				"Kalkweir",
				"Lyderswold",
				"Hornspira",
				"Sommerspira",
				"Brammingwold",
				"Vardegard",
				"Norrewold",
				"Birketorn",
				"Donnerswold",
				"Tangweir",
				"Helviktorn",
				"Torvastorn",
				"Skjoldwold",
				"Eidsviktorn",
				"Halspira",
				"Gerwold",
				"Gunnspira",
				"Asentorn",
				"Hammarwold",
				"Holmwold",
				"Eidarswold",
				"Skallewold",
				"Knorrespira",
				"Linderstorn",
				"Neidspira",
				"Bredaswold"
			],
			[
				"Tonderhovel",
				"Horngard",
				"Grimhaug",
				"Hellehovel",
				"Kalkhovel",
				"Lydersgard",
				"Homsgard",
				"Sommersholm",
				"Brammingholm",
				"Vardegard",
				"Norreholm",
				"Birkehovel",
				"Donnersgard",
				"Tanghaug",
				"Helvikholm",
				"Torvaholm",
				"Skjoldgard",
				"Eidsvikholm",
				"Halshovel",
				"Gerholm",
				"Gunnholm",
				"Asengard",
				"Hammargard",
				"Vikeholm",
				"Skandergard",
				"Skallegard",
				"Varehaug",
				"Gufirsgard",
				"Hafnarsholm",
				"Ragnhaug",
				"Torgeirsholm",
				"Heersgard",
				"Holmhaug",
				"Lundirsholm"
			],
			[
				"Tonderborg",
				"Hornborg",
				"Grimborg",
				"Helleborg",
				"Kalkborg",
				"Lydersborg",
				"Homsborg",
				"Sommersborg",
				"Brammingborg",
				"Vardeborg",
				"Norreborg",
				"Birkeborg",
				"Donnersborg",
				"Tangborg",
				"Helvikborg",
				"Torvaborg",
				"Skjoldborg",
				"Eidsvikborg",
				"Halsborg",
				"Gerborg",
				"Gunnborg",
				"Asenborg",
				"Hammarborg",
				"Skagaborg",
				"Selasborg",
				"Haellborg",
				"Kampaborg",
				"Gufarsborg",
				"Husnarborg",
				"Reistarborg",
				"Geirborg"
			]
		];
		this.m.DraftLists = [
			[
				"apprentice_background",
				"houndmaster_background",
				"militia_background",
				"militia_background",
				"miner_background",
				"vagabond_background",
				"wildman_background",
				"bastard_background",
				"deserter_background",
				"deserter_background",
				"retired_soldier_background",
				"retired_soldier_background"
			],
			[
				"houndmaster_background",
				"brawler_background",
				"gravedigger_background",
				"messenger_background",
				"militia_background",
				"militia_background",
				"ratcatcher_background",
				"vagabond_background",
				"wildman_background",
				"witchhunter_background",
				"bastard_background",
				"deserter_background",
				"deserter_background",
				"raider_background",
				"retired_soldier_background",
				"retired_soldier_background",
				"sellsword_background"
			],
			[
				"apprentice_background",
				"brawler_background",
				"brawler_background",
				"brawler_background",
				"gambler_background",
				"cultist_background",
				"gravedigger_background",
				"graverobber_background",
				"messenger_background",
				"militia_background",
				"militia_background",
				"militia_background",
				"peddler_background",
				"ratcatcher_background",
				"refugee_background",
				"shepherd_background",
				"shepherd_background",
				"vagabond_background",
				"wildman_background",
				"wildman_background",
				"witchhunter_background",
				"bastard_background",
				"bastard_background",
				"deserter_background",
				"deserter_background",
				"raider_background",
				"retired_soldier_background",
				"sellsword_background",
				"sellsword_background",
				"squire_background",
				"swordmaster_background",
				"cripple_background",
				"eunuch_background",
				"hedge_knight_background",
				"hedge_knight_background"
			]
		];
		this.m.FemaleDraftLists = [
			[
				"legend_shieldmaiden_background",
				"female_daytaler_background"
			],
			[
				"legend_shieldmaiden_background",
				"female_bowyer_background",
				"female_daytaler_background",
				"wildwoman_background",
				"witchhunter_background",
				"female_disowned_noble_background"
			],
			[
				"legend_shieldmaiden_background",
				"female_beggar_background",
				"female_bowyer_background",
				"female_daytaler_background",
				"female_farmhand_background",
				"wildwoman_background",
				"witchhunter_background",
				"female_disowned_noble_background"
			]
		];
		this.m.StablesLists = [
			[
				"legend_donkey_background",
				"legend_horse_rouncey"
			],
			[
				"legend_donkey_background",
				"legend_horse_rouncey"
			],
			[
				"legend_donkey_background",
				"legend_horse_rouncey",
				"legend_horse_destrier"
			]
		];
		this.m.Rumors = this.Const.Strings.RumorsTundraSettlement;
	}

});
