::mods_hookExactClass("entity/world/settlements/legends_snow_fort.nut", function(o) {
	o.create = function()
	{
		this.legends_fort.create();
		this.m.Names = [
			[
				"Tonderwold",
				"Hornwold",
				"Grimtorn",
				"Helleweir",
				"Kalkweir",
				"Lyderswold",
				"Hornspira",
				"Sommerspira",
				"Brammingwold",
				"Vardegard",
				"Norrewold",
				"Birketorn",
				"Donnerswold",
				"Tangweir",
				"Helviktorn",
				"Torvastorn",
				"Skjoldwold",
				"Eidsviktorn",
				"Halspira",
				"Gerwold",
				"Gunnspira",
				"Asentorn",
				"Hammarwold",
				"Holmgard",
				"Vallgard",
				"Falkenholm",
				"Glommenwold",
				"Gunnweir",
				"Asatorn",
				"Kungswold",
				"Hagenswold",
				"Lindweir",
				"Hindaswolt",
				"Lokewold",
				"Ringwold",
				"Hakonswold"
			],
			[
				"Tonderhovel",
				"Horngard",
				"Grimhaug",
				"Hellehovel",
				"Kalkhovel",
				"Lydersgard",
				"Homsgard",
				"Sommersholm",
				"Brammingholm",
				"Vardegard",
				"Norreholm",
				"Birkehovel",
				"Donnersgard",
				"Tanghaug",
				"Helvikholm",
				"Torvaholm",
				"Skjoldgard",
				"Eidsvikholm",
				"Halshovel",
				"Gerholm",
				"Gunnholm",
				"Asengard",
				"Hammargard",
				"Vikeholm",
				"Skandergard",
				"Gunhall",
				"Asaholm",
				"Grimmarsholm",
				"Hjalsgard",
				"Kungenshovel",
				"Wallhovel"
			],
			[
				"Tonderborg",
				"Hornborg",
				"Grimborg",
				"Helleborg",
				"Kalkborg",
				"Lydersborg",
				"Homsborg",
				"Sommersborg",
				"Brammingborg",
				"Vardeborg",
				"Norreborg",
				"Birkeborg",
				"Donnersborg",
				"Tangborg",
				"Helvikborg",
				"Torvaborg",
				"Skjoldborg",
				"Eidsvikborg",
				"Halsborg",
				"Gerborg",
				"Gunnborg",
				"Asenborg",
				"Hammarborg",
				"Snekkborg",
				"Groneborg",
				"Ramborg",
				"Vineborg",
				"Hunneborg",
				"Varborg",
				"Kungsborg",
				"Jarlsborg"
			]
		];
		this.m.DraftLists = [
			[
				"houndmaster_background",
				"brawler_background",
				"cultist_background",
				"mason_background",
				"militia_background",
				"militia_background",
				"vagabond_background",
				"wildman_background",
				"witchhunter_background",
				"deserter_background",
				"deserter_background",
				"raider_background",
				"retired_soldier_background",
				"retired_soldier_background"
			],
			[
				"apprentice_background",
				"houndmaster_background",
				"brawler_background",
				"brawler_background",
				"cultist_background",
				"gravedigger_background",
				"mason_background",
				"messenger_background",
				"militia_background",
				"miner_background",
				"monk_background",
				"ratcatcher_background",
				"refugee_background",
				"vagabond_background",
				"vagabond_background",
				"wildman_background",
				"wildman_background",
				"witchhunter_background",
				"deserter_background",
				"raider_background",
				"retired_soldier_background"
			],
			[
				"apprentice_background",
				"brawler_background",
				"gravedigger_background",
				"graverobber_background",
				"mason_background",
				"messenger_background",
				"militia_background",
				"militia_background",
				"militia_background",
				"ratcatcher_background",
				"refugee_background",
				"vagabond_background",
				"vagabond_background",
				"wildman_background",
				"wildman_background",
				"witchhunter_background",
				"witchhunter_background",
				"deserter_background",
				"deserter_background",
				"hedge_knight_background",
				"hedge_knight_background",
				"raider_background",
				"raider_background",
				"raider_background",
				"retired_soldier_background",
				"retired_soldier_background",
				"sellsword_background",
				"squire_background",
				"cripple_background"
			]
		];
		this.m.FemaleDraftLists = [
			[
				"female_beggar_background"
			],
			[
				"female_daytaler_background",
				"wildwoman_background",
				"female_adventurous_noble_background",
				"female_disowned_noble_background"
			],
			[
				"female_daytaler_background",
				"female_servant_background",
				"wildwoman_background",
				"female_adventurous_noble_background",
				"female_disowned_noble_background",
				"female_disowned_noble_background",
				"legend_shieldmaiden_background"
			]
		];
		this.m.StablesLists = [
			[
				"legend_donkey_background",
				"legend_horse_rouncey"
			],
			[
				"legend_donkey_background",
				"legend_horse_rouncey"
			],
			[
				"legend_donkey_background",
				"legend_horse_rouncey",
				"legend_horse_destrier",
				"legend_horse_courser"
			]
		];

		if (this.Const.DLC.Unhold)
		{
			this.m.DraftLists[0].push("beast_hunter_background");
			this.m.DraftLists[1].push("beast_hunter_background");
			this.m.DraftLists[2].push("beast_hunter_background");
		}

		this.m.Rumors = this.Const.Strings.RumorsSnowSettlement;
	}

});
