::mods_hookExactClass("entity/world/settlements/legends_lumber_village.nut", function(o) {
	o.create = function()
	{
		this.legends_village.create();
		this.m.Names = [
			[
				"Westerholz",
				"Langholz",
				"Grossholz",
				"Tanndorf",
				"Waldhain",
				"Elkshorn",
				"Dunkeltal",
				"Eichholz",
				"Eulenkrug",
				"Nordholz",
				"Finsterwalde",
				"Damwald",
				"Tannheim",
				"Filzmoos",
				"Dunkelwald",
				"Hagermoos",
				"Neufarn",
				"Taubenmoos",
				"Waidhof",
				"Waidtal",
				"Eichendorf",
				"Holzschlag",
				"Hirschbach",
				"Friedewald",
				"Talbach",
				"Finsterweiler",
				"Tannenweiler",
				"Weilersheim",
				"Grunforst",
				"Tiefenforst",
				"Eschbach",
				"Grunenbach",
				"Nesselwald",
				"Kleinholz",
				"Jungholz",
				"Eisenholz",
				"Ehrwalden",
				"Ettelwald"
			],
			[
				"Westerholz",
				"Langholz",
				"Grossholz",
				"Tanndorf",
				"Waldhain",
				"Elkshorn",
				"Dunkeltal",
				"Eichholz",
				"Eulenkrug",
				"Nordholz",
				"Finsterwalde",
				"Damwald",
				"Tannheim",
				"Filzmoos",
				"Dunkelwald",
				"Hagermoos",
				"Neufarn",
				"Taubenmoos",
				"Waidhof",
				"Waidtal",
				"Eichendorf",
				"Holzschlag",
				"Hirschbach",
				"Friedewald",
				"Talbach",
				"Finsterweiler",
				"Tannenweiler",
				"Weilersheim",
				"Grunforst",
				"Tiefenforst",
				"Schwarzforst"
			],
			[
				"Holzmark",
				"Dustermark",
				"Tannstadt",
				"Waldland",
				"Finsterstadt",
				"Dunkelmark",
				"Eichstadt",
				"Eulenmark",
				"Hageland",
				"Waidstadt",
				"Fahrnstadt",
				"Hirschmark",
				"Weilerstadt",
				"Forstland",
				"Tiefenmark",
				"Grunstadt",
				"Thalstadt",
				"Grunland",
				"Waldmark",
				"Finstermark",
				"Konigswald",
				"Grafenhain",
				"Konigshain"
			]
		];
		this.m.DraftLists = [
			[
				"apprentice_background",
				"bowyer_background",
				"bowyer_background",
				"butcher_background",
				"daytaler_background",
				"lumberjack_background",
				"lumberjack_background",
				"lumberjack_background",
				"poacher_background",
				"poacher_background",
				"poacher_background",
				"wildman_background",
				"hunter_background",
				"hunter_background",
				"tailor_background",
				"apprentice_background",
				"lumberjack_background",
				"lumberjack_background",
				"lumberjack_background",
				"poacher_background",
				"poacher_background",
				"poacher_background",
				"wildman_background",
				"hunter_background",
				"hunter_background"
			],
			[
				"beggar_background",
				"bowyer_background",
				"bowyer_background",
				"brawler_background",
				"butcher_background",
				"daytaler_background",
				"historian_background",
				"hunter_background",
				"hunter_background",
				"killer_on_the_run_background",
				"lumberjack_background",
				"lumberjack_background",
				"lumberjack_background",
				"militia_background",
				"flagellant_background",
				"poacher_background",
				"poacher_background",
				"tailor_background",
				"vagabond_background",
				"wildman_background",
				"witchhunter_background",
				"cripple_background",
				"eunuch_background",
				"brawler_background",
				"butcher_background",
				"historian_background",
				"hunter_background",
				"hunter_background",
				"killer_on_the_run_background",
				"lumberjack_background",
				"lumberjack_background",
				"lumberjack_background",
				"militia_background",
				"flagellant_background",
				"poacher_background",
				"poacher_background",
				"vagabond_background",
				"wildman_background",
				"wildman_background",
				"witchhunter_background",
				"cripple_background",
				"eunuch_background"
			],
			[
				"apprentice_background",
				"beggar_background",
				"brawler_background",
				"cultist_background",
				"daytaler_background",
				"hunter_background",
				"hunter_background",
				"hunter_background",
				"killer_on_the_run_background",
				"lumberjack_background",
				"lumberjack_background",
				"lumberjack_background",
				"militia_background",
				"militia_background",
				"minstrel_background",
				"peddler_background",
				"poacher_background",
				"poacher_background",
				"poacher_background",
				"ratcatcher_background",
				"refugee_background",
				"tailor_background",
				"thief_background",
				"vagabond_background",
				"wildman_background",
				"witchhunter_background",
				"bastard_background",
				"hedge_knight_background",
				"retired_soldier_background",
				"cripple_background",
				"eunuch_background",
				"legend_inventor_background"
			]
		];
		this.m.FemaleDraftLists = [
			[
				"wildwoman_background",
				"female_bowyer_background",
				"female_bowyer_background",
				"female_butcher_background",
				"female_daytaler_background",
				"female_tailor_background"
			],
			[
				"wildwoman_background",
				"female_beggar_background",
				"female_bowyer_background",
				"female_bowyer_background",
				"female_daytaler_background",
				"female_tailor_background"
			],
			[
				"legend_shieldmaiden_background",
				"female_bowyer_background",
				"female_bowyer_background",
				"female_bowyer_background",
				"female_butcher_background",
				"female_servant_background",
				"wildwoman_background",
				"female_disowned_noble_background"
			]
		];
		this.m.StablesLists = [
			[
				"legend_donkey_background",
				"legend_horse_rouncey"
			],
			[
				"legend_donkey_background",
				"legend_horse_rouncey"
			],
			[
				"legend_donkey_background",
				"legend_horse_rouncey"
			]
		];

		if (this.Const.DLC.Unhold)
		{
			this.m.DraftLists[0].push("beast_hunter_background");
			this.m.DraftLists[1].push("beast_hunter_background");
			this.m.DraftLists[2].push("beast_hunter_background");
			this.m.DraftLists[2].push("beast_hunter_background");
		}

		this.m.Rumors = this.Const.Strings.RumorsForestSettlement;
		this.m.ProduceString = "wood";
	}

});
