::mods_hookExactClass("entity/world/settlements/legends_farming_village.nut", function(o) {
	o.create = function()
	{
		this.legends_village.create();
		this.m.Names = [
			[
				"Weidefeld",
				"Hemmeln",
				"Saxdorf",
				"Kochendorf",
				"Altenhof",
				"Weidenau",
				"Schnellen",
				"Neudorf",
				"Freidorf",
				"Weissenhaus",
				"Muhlenheim",
				"Grunfelde",
				"Ivendorf",
				"Ohnemenschen",
				"Kornstadt",
				"Ausbeute",
				"Feldgehen",
				"Tierbauernhof",
				"Grafenheide",
				"Hermannshof",
				"Koppeldorf",
				"Meiding",
				"Varel",
				"Durbach",
				"Dreifelden",
				"Bockhorn",
				"Hufschlag",
				"Hage",
				"Wagenheim",
				"Harlingen",
				"Wiese",
				"Wiesendorf",
				"Markdorf",
				"Heuweiler",
				"Bitterfeld",
				"Neuenried",
				"Auenbach",
				"Adelshofen",
				"Allersdorf",
				"Brunnendorf",
				"Ochsenhausen",
				"Weingarten",
				"Konigsfeld",
				"Rosenhof",
				"Weidenbach"
			],
			[
				"Weidefeld",
				"Hemmeln",
				"Saxdorf",
				"Kochendorf",
				"Altenhof",
				"Schnellen",
				"Neudorf",
				"Freidorf",
				"Durbach",
				"Weissenhaus",
				"Muhlenheim",
				"Grunfelde",
				"Ivendorf",
				"Weidenau",
				"Grafenheide",
				"Hermannshof",
				"Koppeldorf",
				"Meiding",
				"Varel",
				"Dreifelden",
				"Bockhorn",
				"Hufschlag",
				"Hage",
				"Wagenheim",
				"Harlingen",
				"Wiese",
				"Wiesendorf",
				"Markdorf",
				"Heuweiler",
				"Bitterfeld"
			],
			[
				"Weidemark",
				"Hemmelmark",
				"Kochenland",
				"Altenstadt",
				"Schnellmark",
				"Neumark",
				"Freistadt",
				"Weissenstadt",
				"Muhlstadt",
				"Grunmark",
				"Ivenstadt",
				"Grafenstadt",
				"Konigsland",
				"Dreigrafen",
				"Koppelstadt",
				"Varelmark",
				"Hageland",
				"Dulmen",
				"Wiesenmark",
				"Heuland",
				"Auenmark",
				"Kornstadt",
				"Konigsheim",
				"Wedelmark",
				"Albstadt",
				"Kammersmark",
				"Adelsland",
				"Heldenland",
				"Dinkelsmark",
				"Schwanstadt",
				"Grunhain"
			]
		];
		this.m.DraftLists = [
			[
				"beggar_background",
				"daytaler_background",
				"daytaler_background",
				"farmhand_background",
				"farmhand_background",
				"farmhand_background",
				"farmhand_background",
				"miller_background",
				"miller_background",
				"ratcatcher_background",
				"tailor_background",
				"vagabond_background",
				"poacher_background",
				"ratcatcher_background",
				"vagabond_background",
				"poacher_background"
			],
			[
				"apprentice_background",
				"beggar_background",
				"butcher_background",
				"gambler_background",
				"daytaler_background",
				"daytaler_background",
				"farmhand_background",
				"farmhand_background",
				"farmhand_background",
				"juggler_background",
				"messenger_background",
				"militia_background",
				"militia_background",
				"miller_background",
				"miller_background",
				"minstrel_background",
				"ratcatcher_background",
				"refugee_background",
				"servant_background",
				"tailor_background",
				"vagabond_background",
				"retired_soldier_background",
				"apprentice_background",
				"butcher_background",
				"gambler_background",
				"juggler_background",
				"messenger_background",
				"militia_background",
				"militia_background",
				"minstrel_background",
				"ratcatcher_background",
				"refugee_background",
				"vagabond_background",
				"retired_soldier_background"
			],
			[
				"swordmaster_background",
				"apprentice_background",
				"caravan_hand_background",
				"gambler_background",
				"historian_background",
				"juggler_background",
				"militia_background",
				"militia_background",
				"minstrel_background",
				"minstrel_background",
				"peddler_background",
				"ratcatcher_background",
				"refugee_background",
				"shepherd_background",
				"vagabond_background",
				"bastard_background",
				"hedge_knight_background",
				"raider_background",
				"retired_soldier_background",
				"sellsword_background",
				"squire_background",
				"swordmaster_background",
				"legend_inventor_background"
			]
		];
		this.m.FemaleDraftLists = [
			[
				"female_beggar_background",
				"female_daytaler_background",
				"female_daytaler_background",
				"female_farmhand_background",
				"female_farmhand_background",
				"female_farmhand_background",
				"female_farmhand_background",
				"female_miller_background",
				"female_miller_background",
				"female_tailor_background"
			],
			[
				"female_beggar_background",
				"female_daytaler_background",
				"female_daytaler_background",
				"female_farmhand_background",
				"female_farmhand_background",
				"female_farmhand_background",
				"female_miller_background",
				"female_miller_background",
				"female_servant_background",
				"female_tailor_background"
			],
			[
				"female_beggar_background",
				"female_beggar_background",
				"female_butcher_background",
				"female_daytaler_background",
				"female_daytaler_background",
				"female_farmhand_background",
				"female_farmhand_background",
				"female_farmhand_background",
				"female_farmhand_background",
				"female_miller_background",
				"female_miller_background",
				"female_miller_background",
				"female_servant_background",
				"female_tailor_background",
				"female_adventurous_noble_background"
			]
		];
		this.m.StablesLists = [
			[
				"legend_donkey_background",
				"legend_donkey_background"
			],
			[
				"legend_donkey_background",
				"legend_donkey_background",
				"legend_horse_rouncey"
			],
			[
				"legend_donkey_background",
				"legend_donkey_background",
				"legend_horse_rouncey"
			]
		];
		this.m.Rumors = this.Const.Strings.RumorsFarmingSettlement;
	}

	o.getHousesMin = function()
	{
		switch(this.m.Size)
		{
		case 1:
			return 1;

		case 2:
			return 2;

		case 3:
			return 4;
		}

		return 1;
	}

});
