::mods_hookExactClass("entity/world/settlements/legends_forest_fort.nut", function(o) {
	o.create = function()
	{
		this.legends_fort.create();
		this.m.Names = [
			[
				"Holzwacht",
				"Tannwall",
				"Waldwacht",
				"Hainturm",
				"Dunkelwacht",
				"Eichwacht",
				"Waidschanze",
				"Fahrnwacht",
				"Mooswehr",
				"Forstwehr",
				"Eulenwacht",
				"Fuchsturm",
				"Finsterwall",
				"Dusterschanze",
				"Finsterwehr",
				"Dornwall",
				"Farnwacht",
				"Grunwall",
				"Eulenturm",
				"Wildwacht",
				"Steinforst",
				"Haselwacht",
				"Nebelwacht",
				"Hirschturm",
				"Schwarzwacht",
				"Steinweiler",
				"Erlenwall",
				"Eibenwacht",
				"Haselwehr",
				"Waldenwehr"
			],
			[
				"Holzburg",
				"Tannburg",
				"Waldburg",
				"Hainburg",
				"Dunkelburg",
				"Finsterburg",
				"Eichburg",
				"Waidburg",
				"Fahrnburg",
				"Moosburg",
				"Forstburg",
				"Eulenburg",
				"Fuchsburg",
				"Dusterburg",
				"Dornburg",
				"Grunburg",
				"Buchenburg",
				"Haselburg",
				"Breitenburg",
				"Nesselburg",
				"Wurzelburg",
				"Bieberburg",
				"Katzenburg",
				"Wolfsburg",
				"Natternburg",
				"Findelsburg"
			],
			[
				"Waldfeste",
				"Tannenfeste",
				"Schlangenfeste",
				"Hainfeste",
				"Dunkelfeste",
				"Finsterfeste",
				"Eichfeste",
				"Eibenfeste",
				"Waidfeste",
				"Eulenfeste",
				"Eberfeste",
				"Fahrnfeste",
				"Moosfeste",
				"Forstfeste",
				"Dusterfeste",
				"Dornfeste",
				"Grunfeste",
				"Falkenfeste",
				"Salamanderfeste",
				"Lerchenfeste",
				"Laubfeste",
				"Erlenfeste",
				"Nadelfeste",
				"Waldachfeste",
				"Hornfeste",
				"Klarbachfeste",
				"Eisbachfeste",
				"Fichtenwall"
			]
		];
		this.m.DraftLists = [
			[
				"apprentice_background",
				"houndmaster_background",
				"brawler_background",
				"hunter_background",
				"hunter_background",
				"lumberjack_background",
				"militia_background",
				"militia_background",
				"wildman_background",
				"bastard_background",
				"deserter_background",
				"deserter_background",
				"retired_soldier_background",
				"retired_soldier_background"
			],
			[
				"apprentice_background",
				"houndmaster_background",
				"brawler_background",
				"daytaler_background",
				"gravedigger_background",
				"hunter_background",
				"lumberjack_background",
				"lumberjack_background",
				"messenger_background",
				"militia_background",
				"militia_background",
				"wildman_background",
				"witchhunter_background",
				"bastard_background",
				"deserter_background",
				"retired_soldier_background",
				"squire_background"
			],
			[
				"apprentice_background",
				"brawler_background",
				"gambler_background",
				"gravedigger_background",
				"hunter_background",
				"hunter_background",
				"lumberjack_background",
				"lumberjack_background",
				"messenger_background",
				"militia_background",
				"militia_background",
				"militia_background",
				"ratcatcher_background",
				"refugee_background",
				"wildman_background",
				"witchhunter_background",
				"bastard_background",
				"deserter_background",
				"deserter_background",
				"hedge_knight_background",
				"raider_background",
				"raider_background",
				"retired_soldier_background",
				"retired_soldier_background",
				"sellsword_background",
				"squire_background",
				"squire_background",
				"swordmaster_background",
				"cripple_background"
			]
		];
		this.m.FemaleDraftLists = [
			[
				"legend_shieldmaiden_background",
				"female_bowyer_background",
				"female_daytaler_background"
			],
			[
				"legend_shieldmaiden_background",
				"female_bowyer_background",
				"female_bowyer_background",
				"female_butcher_background",
				"wildwoman_background",
				"female_disowned_noble_background",
				"female_disowned_noble_background"
			],
			[
				"female_beggar_background",
				"female_bowyer_background",
				"female_bowyer_background",
				"female_bowyer_background",
				"wildwoman_background",
				"female_disowned_noble_background",
				"female_disowned_noble_background",
				"legend_shieldmaiden_background",
				"legend_shieldmaiden_background"
			]
		];
		this.m.StablesLists = [
			[
				"legend_donkey_background",
				"legend_horse_rouncey"
			],
			[
				"legend_donkey_background",
				"legend_horse_rouncey"
			],
			[
				"legend_donkey_background",
				"legend_horse_rouncey",
				"legend_horse_destrier",
				"legend_horse_courser"
			]
		];

		if (this.Const.DLC.Unhold)
		{
			this.m.DraftLists[0].push("beast_hunter_background");
			this.m.DraftLists[1].push("beast_hunter_background");
			this.m.DraftLists[2].push("beast_hunter_background");
			this.m.DraftLists[2].push("beast_hunter_background");
		}

		this.m.Rumors = this.Const.Strings.RumorsForestSettlement;
	}

});
